(package-initialize)

(require 'cask "~/.cask/cask.el")
(cask-initialize)

;; Load path
(add-to-list 'load-path (expand-file-name "site-lisp" user-emacs-directory))
(let ((default-directory "~/.emacs.d/site-lisp/"))
  (normal-top-level-add-subdirs-to-load-path))

(load "appearance")
(load "misc")
(load "company-custom")
(load "eldoc-custom")
(load "paredit-custom")
(load "yasnippet-custom")
(load "magit-custom")
(load "helm-custom")
(load "projectile-custom")
(load "gtags-custom")
(load "semantic-custom")
(load "neotree-custom")
(load "powerline-custom")
(load "sh-custom")
(load "perl-custom")
(load "evil-custom")
(load "org-custom")
(load "haskell-custom")
(load "clojure-custom")
(load "ruby-custom")
(load "octave-custom")
(load "ocaml-custom")
(load "elm-custom")
(load "javascript-custom")
