# ssh
export SSH_KEY_PATH="~/.ssh/rsa_id"

autoload -U zmv
alias zmv='noglob zmv -W'

# Powerline
function powerline_precmd() {
  PS1="$(powerline-go -error $? -shell zsh -hostname-only-if-ssh -cwd-max-depth 4)"
}

function install_powerline_precmd() {
  for s in "${precmd_functions[@]}"; do
    if [ "$s" = "powerline_precmd" ]; then
      return
    fi
  done
  precmd_functions+=(powerline_precmd)
}

if [ "$TERM" != "linux" ]; then
  install_powerline_precmd
fi
