#!/usr/bin/env bash

os=$(uname -s)

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias ll='ls -l'
alias la='ls -la'
alias duchs='du -chs'
alias ducks='du -cks'
alias less='less -RN'
alias e='emacs'
alias te='emacs -nw'
alias ec='emacsclient -c'
alias tec='emacsclient -c -nw'
alias ed='emacs --daemon'
alias tmux='tmux -u -2'
command -v rlwrap &>/dev/null && alias ocaml='rlwrap ocaml'
command -v rlwrap &>/dev/null && alias q='rlwrap q'

if grep -q --color=auto 1 <(echo 1); then
  alias grep='grep --color=auto'
  alias egrep='egrep --color=auto'
  alias fgrep='fgrep --color=auto'
fi

if ls --color=auto . &>/dev/null; then
  alias ls='ls --color=auto'
  alias ll='ls -l --color=auto'
  alias la='ls -la --color=auto'
fi

if [[ $os = Linux ]]; then
  alias docker-rm='docker ps -a -q --filter status=exited | xargs --no-run-if-empty docker rm'
  alias docker-rmi="docker images | grep '^<none>' | awk '{print $3}' | xargs --no-run-if-empty docker rm"
elif [[ $os = Darwin ]]; then
  alias docker-rm='docker rm -f $(docker ps -a -q --filter status=exited) 2>/dev/null'
  alias docker-rmi="docker rmi -f \$(docker images | grep '^<none>' | awk '{print $3}') 2>/dev/null"
fi

unset os
