syntax on
if has('unix')
  if system('uname') =~ 'Darwin'
    set guifont=Inconsolata\ for\ Powerline\ 16
  else
    set guifont=Inconsolata\ for\ Powerline\ Medium\ 14
  endif
elseif has('windows')
  set guifont=Inconsolata_for_Powerline:h12
endif
set encoding=utf-8
if exists('$TMUX')
  set term=screen-256color
endif
colorscheme nord

" Show line numbers
set number

" Show partial commands in the last line of the screen
set showcmd

" Customize backspaces
set backspace=indent,eol,start

" Formatting options
set autoindent
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2
set shiftround
set tw=78

" Allow % to bounce between angles too
set matchpairs+=<:>

" Enable filetype detection, plugin and indent
filetype plugin indent on
au BufRead,BufNewFile *.ml,*.mli,*.mf,*.mfi compiler ocaml

" Omni completion
set ofu=syntaxcomplete#Complete

" NERD tree
nnoremap <silent> <F8> :NERDTreeToggle<CR>

" vim-airline
let g:airline_theme = 'nord'
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1

if has('autocmd')
  autocmd BufReadPost fugitive://* set bufhidden=delete
endif

" Automatically update diff
autocmd BufWritePost * if &diff == 1 | diffupdate | endif

" Easymotion
let g:EasyMotion_do_mapping = 0 " Disable default mappings
let g:EasyMotion_smartcase = 1
let g:EasyMotion_startofline = 0 " keep cursor column when JK motion
nmap s <Plug>(easymotion-overwin-f2)
map <Leader>l <Plug>(easymotion-lineforward)
map <Leader>j <Plug>(easymotion-j)
map <Leader>k <Plug>(easymotion-k)
map <Leader>h <Plug>(easymotion-linebackward)
